import React from 'react';
import { SectionHeader, Card, Callout, Badge, EmptyState } from '../components/primitives';
import { KpiStrip, StatTile } from '../components/Kpi';
import { shadow, benchmark, armRow } from '../../lib/data';

export const metadata = { title: 'Recoup — what we refused' };

export default function RefusedPage() {
  const refused = shadow.refused;
  const strawViol = armRow(benchmark.technical, 'Guard Violations')?.arms.NaiveUnbounded;
  const strawMean = strawViol?.mean ?? 287;

  return (
    <div className="stack">
      <SectionHeader
        kicker="What we refused"
        title="Accounts the agent examined and refused to chase"
        description="Every refusal is a case classified as structurally unrecoverable or consent-withdrawn. Chasing it would burn fees and regulatory goodwill for zero expected recovery."
      />

      <Callout title="Two populations — measured separately">
        <ul style={{ margin: 0, paddingLeft: '1.1rem' }}>
          <li>
            <strong>Shadow cohort (this page):</strong> {shadow.refused_count} of {shadow.total_events}{' '}
            <strong>synthetic</strong> webhook events ({shadow.refused_pct}%) halted at Level&nbsp;0. These are
            synthetic-realistic records built to match Razorpay&apos;s error schema and published failure-reason
            mix — <strong>not production traffic</strong>. IDs are <code>evt_synth_*</code>. Committed artifact:{' '}
            <code>docs/shadow-decisions.jsonl</code>, regenerated by <code>make shadow</code>.
          </li>
          <li>
            <strong>CRN simulation:</strong> bounded execution refuses{' '}
            <strong>{armRow(benchmark.technical, 'Declined Chases')?.arms.NaiveBounded.text}</strong> of{' '}
            {benchmark.cases_per_seed} cases per batch — a different, simulated population over{' '}
            {benchmark.seeds} seeds.
          </li>
        </ul>
        <p style={{ marginTop: '0.6rem' }}>
          No customer identities exist in either population — the simulator and the synthetic feed carry none.
          Nothing here is masked, and nothing is invented.
        </p>
      </Callout>

      <KpiStrip>
        <StatTile label="Refused at Level 0" value={String(shadow.refused_count)} sub={`${shadow.refused_pct}% of ${shadow.total_events} synthetic events`} />
        <StatTile label="Policy legality" value={`${shadow.legal_compliance_pct}%`} sub="0 TRAI / cooling-off / DND violations across the run" />
        <StatTile label="Taxonomy coverage" value={`${shadow.taxonomy_coverage_pct}%`} sub={`${shadow.mapped_events}/${shadow.total_events} events mapped to an actionable failure code`} />
      </KpiStrip>

      <Card label="Guard violations per batch — the cost of not refusing">
        <div style={{ display: 'grid', gap: '0.9rem', maxWidth: 560 }}>
          <ViolationBar label="Recoup (bounded)" value={0} max={strawMean} display="0" tone="pos" />
          <ViolationBar label="Unbounded strawman" value={strawMean} max={strawMean} display={strawViol?.text ?? String(strawMean)} tone="neg" />
        </div>
        <p className="muted" style={{ fontSize: '0.86rem', marginTop: '0.9rem' }}>
          The unbounded arm chases every failed payment, including the ones on this page. It recovers less net
          capital and violates contact-hour, cooling-off and DND rules {strawViol?.text ?? ''} times per batch.
        </p>
      </Card>

      <Card label={`Refused synthetic events (${refused.length} of ${shadow.total_events})`}>
        <p className="muted" style={{ fontSize: '0.88rem', marginBottom: '0.9rem' }}>
          Synthetic-realistic shadow cohort — <strong>not production traffic</strong> (
          <code>evt_synth_*</code>, generated from Razorpay&apos;s error schema). All{' '}
          {refused.length} refusals are <strong>mandate revocations</strong>: consent explicitly withdrawn, so
          every downstream action is prohibited. Source: <code>{shadow.generated_from}</code>.
        </p>
        {refused.length === 0 ? (
          <EmptyState title="No refusal records">
            The committed shadow run contains no declined chases, and the live API does not expose shadow
            decisions. Run <code>make shadow</code> to regenerate.
          </EmptyState>
        ) : (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Event</th>
                  <th>Payment</th>
                  <th scope="col">Reason refused</th>
                  <th>Mapped</th>
                  <th>Legally compliant</th>
                </tr>
              </thead>
              <tbody>
                {refused.map((e) => (
                  <tr key={e.event_id}>
                    <td><code>{e.event_id}</code></td>
                    <td><code>{e.payment_id}</code></td>
                    <th scope="row" style={{ fontWeight: 500 }}>
                      <Badge tone="neg">{(e.failure_code ?? e.unmapped_reason ?? 'unmapped').replace(/_/g, ' ')}</Badge>
                    </th>
                    <td>{e.is_mapped ? 'yes' : <Badge tone="warn">no</Badge>}</td>
                    <td>{e.is_legally_compliant ? <Badge tone="pos">yes</Badge> : <Badge tone="neg">no</Badge>}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </Card>
    </div>
  );
}

function ViolationBar({
  label,
  value,
  max,
  display,
  tone,
}: {
  label: string;
  value: number;
  max: number;
  display: string;
  tone: 'pos' | 'neg';
}) {
  const pct = max > 0 ? Math.max((value / max) * 100, value === 0 ? 0 : 2) : 0;
  const color = tone === 'pos' ? 'var(--pos)' : 'var(--neg)';
  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.82rem', marginBottom: '0.3rem' }}>
        <span className="muted">{label}</span>
        <span className="num" style={{ color }}>{display}</span>
      </div>
      <div style={{ height: 10, background: 'var(--bg)', border: '1px solid var(--border)', borderRadius: 4, overflow: 'hidden' }}>
        <div style={{ width: `${pct}%`, height: '100%', background: color, borderRadius: 3 }} />
      </div>
    </div>
  );
}
